import os, sys
SCRIPT_DIR = os.path.abspath(os.path.dirname(os.path.realpath(__file__)))
kantipur_folder = os.path.normpath(os.path.join(SCRIPT_DIR, '..', 'src'))
sys.path.append(kantipur_folder)

import codecs
from kantipur import *

kantipurTestCases = [
    {'kantipur': u"", 'unicode': u""},

    # individual characters (whole kantipur map)
    {'kantipur': u"!", 'unicode': u"१"},
    {'kantipur': u'"', 'unicode': u"ू"},
    {'kantipur': u"#", 'unicode': u"३"},
    {'kantipur': u"$", 'unicode': u"४"},
    {'kantipur': u"%", 'unicode': u"५"},
    {'kantipur': u"&", 'unicode': u"७"},
    {'kantipur': u"'", 'unicode': u"ु"},
    {'kantipur': u"(", 'unicode': u"९"},
    {'kantipur': u")", 'unicode': u"०"},
    {'kantipur': u"*", 'unicode': u"८"},
    {'kantipur': u"+", 'unicode': u"ं"},
    {'kantipur': u",", 'unicode': u","},
    {'kantipur': u"-", 'unicode': u"("},
    {'kantipur': u".", 'unicode': u"।"},
    {'kantipur': u"/", 'unicode': u"र"},
    {'kantipur': u"0", 'unicode': u"ण्"},
    {'kantipur': u"1", 'unicode': u"ज्ञ"},
    {'kantipur': u"2", 'unicode': u"द्द"},
    {'kantipur': u"3", 'unicode': u"घ"},
    {'kantipur': u"4", 'unicode': u"द्ध"},
    {'kantipur': u"5", 'unicode': u"छ"},
    {'kantipur': u"6", 'unicode': u"ट"},
    {'kantipur': u"7", 'unicode': u"ठ"},
    {'kantipur': u"8", 'unicode': u"ड"},
    {'kantipur': u"9", 'unicode': u"ढ"},
    {'kantipur': u":", 'unicode': u"स्"},
    {'kantipur': u";", 'unicode': u"स"},
    {'kantipur': u"<", 'unicode': u"?"},
    {'kantipur': u"=", 'unicode': u"."},
    {'kantipur': u">", 'unicode': u"श्र"},
    {'kantipur': u"?", 'unicode': u"रु"},
    {'kantipur': u"@", 'unicode': u"२"},
    {'kantipur': u"A", 'unicode': u"ब्"},
    {'kantipur': u"B", 'unicode': u"द्य"},
    {'kantipur': u"C", 'unicode': u"ऋ"},
    {'kantipur': u"D", 'unicode': u"म्"},
    {'kantipur': u"E", 'unicode': u"भ्"},
    {'kantipur': u"F", 'unicode': u"ा"},
    {'kantipur': u"G", 'unicode': u"न्"},
    {'kantipur': u"H", 'unicode': u"ज्"},
    {'kantipur': u"I", 'unicode': u"क्ष्"},
    {'kantipur': u"J", 'unicode': u"व्"},
    {'kantipur': u"K", 'unicode': u"प्"},
    {'kantipur': u"L", 'unicode': u"ी"},
    {'kantipur': u"M", 'unicode': u":"},
    {'kantipur': u"N", 'unicode': u"ल्"},
    {'kantipur': u"O", 'unicode': u"इ"},
    {'kantipur': u"P", 'unicode': u"ए"},
    {'kantipur': u"Q", 'unicode': u"त्त"},
    {'kantipur': u"R", 'unicode': u"च्"},
    {'kantipur': u"S", 'unicode': u"क्"},
    {'kantipur': u"T", 'unicode': u"त्"},
    {'kantipur': u"U", 'unicode': u"ग्"},
    {'kantipur': u"V", 'unicode': u"ख्"},
    {'kantipur': u"W", 'unicode': u"ध्"},
    {'kantipur': u"X", 'unicode': u"ह्"},
    {'kantipur': u"Y", 'unicode': u"थ्"},
    {'kantipur': u"Z", 'unicode': u"श्"},
    {'kantipur': u"[", 'unicode': u"ृ"},
    {'kantipur': u"\\", 'unicode': u"्"},
    {'kantipur': u"]", 'unicode': u"े"},
    {'kantipur': u"^", 'unicode': u"६"},
    {'kantipur': u"_", 'unicode': u")"},
    {'kantipur': u"`", 'unicode': u"ञ"},
    {'kantipur': u"a", 'unicode': u"ब"},
    {'kantipur': u"b", 'unicode': u"द"},
    {'kantipur': u"c", 'unicode': u"अ"},
    {'kantipur': u"d", 'unicode': u"म"},
    {'kantipur': u"e", 'unicode': u"भ"},
    {'kantipur': u"f", 'unicode': u"ा"},
    {'kantipur': u"g", 'unicode': u"न"},
    {'kantipur': u"h", 'unicode': u"ज"},
    {'kantipur': u"i", 'unicode': u"ष्"},
    {'kantipur': u"j", 'unicode': u"व"},
    {'kantipur': u"k", 'unicode': u"प"},
    {'kantipur': u"l", 'unicode': u"ि"},
    {'kantipur': u"m", 'unicode': u"m"}, # no matching unicode single character
    {'kantipur': u"n", 'unicode': u"ल"},
    {'kantipur': u"o", 'unicode': u"य"},
    {'kantipur': u"p", 'unicode': u"उ"},
    {'kantipur': u"q", 'unicode': u"त्र"},
    {'kantipur': u"r", 'unicode': u"च"},
    {'kantipur': u"s", 'unicode': u"क"},
    {'kantipur': u"t", 'unicode': u"त"},
    {'kantipur': u"u", 'unicode': u"ग"},
    {'kantipur': u"v", 'unicode': u"ख"},
    {'kantipur': u"w", 'unicode': u"ध"},
    {'kantipur': u"x", 'unicode': u"ह"},
    {'kantipur': u"y", 'unicode': u"थ"},
    {'kantipur': u"z", 'unicode': u"श"},
    {'kantipur': u"{", 'unicode': u"र्"},
    {'kantipur': u"|", 'unicode': u"्र"},
    {'kantipur': u"}", 'unicode': u"ै"},
    {'kantipur': u"~", 'unicode': u"ञ्"},
    {'kantipur': u" ", 'unicode': u""},
    {'kantipur': u"¡", 'unicode': u"ज्ञ्"},
    {'kantipur': u"¢", 'unicode': u"द्घ"},
    {'kantipur': u"£", 'unicode': u"घ्"},
    {'kantipur': u"¥", 'unicode': u"र्‍"},
    {'kantipur': u"§", 'unicode': u"ट्ट"},
    {'kantipur': u"¨", 'unicode': u"ङ्ग"},
    {'kantipur': u"ª", 'unicode': u"ङ"},
    {'kantipur': u"«", 'unicode': u"्र"},
    {'kantipur': u"¬", 'unicode': u"…"},
    {'kantipur': u"®", 'unicode': u"र"},
    {'kantipur': u"°", 'unicode': u"ड्ढ"},
    {'kantipur': u"±", 'unicode': u"+"},
    {'kantipur': u"´", 'unicode': u"झ"},
    {'kantipur': u"¶", 'unicode': u"ठ्ठ"},
    {'kantipur': u"¿", 'unicode': u"रू"},
    {'kantipur': u"Â", 'unicode': u"र"},
    {'kantipur': u"Æ", 'unicode': u"”"},
    {'kantipur': u"È", 'unicode': u"ष"},
    {'kantipur': u"Ë", 'unicode': u"ङ्ग"},
    {'kantipur': u"Ì", 'unicode': u"न्न"},
    {'kantipur': u"Í", 'unicode': u"ङ्क"},
    {'kantipur': u"Ò", 'unicode': u"…"},
    {'kantipur': u"Ô", 'unicode': u"क्ष"},
    {'kantipur': u"Ø", 'unicode': u"य"},
    {'kantipur': u"Ú", 'unicode': u"’"},
    {'kantipur': u"ß", 'unicode': u"द्म"},
    {'kantipur': u"å", 'unicode': u"द्व"},
    {'kantipur': u"æ", 'unicode': u"“"},
    {'kantipur': u"ç", 'unicode': u"ॐ"},
    {'kantipur': u"÷", 'unicode': u"/"},
    {'kantipur': u"ø", 'unicode': u"य्"},
    {'kantipur': u"ı", 'unicode': u"द्र"},
    {'kantipur': u"Œ", 'unicode': u"त्त्"},
    {'kantipur': u"œ", 'unicode': u"त्र्"},
    {'kantipur': u"˘", 'unicode': u"श्र्"},
    {'kantipur': u"˚", 'unicode': u"फ"},
    {'kantipur': u"˜", 'unicode': u"ऽ"},
    {'kantipur': u"‐", 'unicode': u"("},
    {'kantipur': u"–", 'unicode': u"–"},
    {'kantipur': u"—", 'unicode': u"—"},
    {'kantipur': u"‘", 'unicode': u"‘"},
    {'kantipur': u"’", 'unicode': u"’"},
    {'kantipur': u"“", 'unicode': u"ँ"},
    {'kantipur': u"„", 'unicode': u"ध्र"},
    {'kantipur': u"•", 'unicode': u"ड्ड"},
    {'kantipur': u"…", 'unicode': u"‘"},
    {'kantipur': u"‰", 'unicode': u"झ्"},
    {'kantipur': u"‹", 'unicode': u"ङ्घ"},
    {'kantipur': u"›", 'unicode': u"ऽ"},
    {'kantipur': u"⁄", 'unicode': u"!"},
    {'kantipur': u"∞", 'unicode': u"%"},
    {'kantipur': u"≈", 'unicode': u"ह्"},
    {'kantipur': u"≠", 'unicode': u"="},
    {'kantipur': u"≤", 'unicode': u";"},
    {'kantipur': u"≥", 'unicode': u"."},
    {'kantipur': u"⋲", 'unicode': u"ह्"},
    {'kantipur': u"◊", 'unicode': u"ङ्ख"},
    {'kantipur': u"", 'unicode': u"फ्"},
    {'kantipur': u"", 'unicode': u"ट्ठ"},
    {'kantipur': u"Î", 'unicode': u"फ्"},
    {'kantipur': u"¤", 'unicode': u"झ्"},
    {'kantipur': u"™", 'unicode': u"र"},
    {'kantipur': u"/\\", 'unicode': u"र्"},
    {'kantipur': u"/\\o", 'unicode': u"ऱ्य"},

    # words
    {'kantipur': u"l:j|m", 'unicode': u"स्क्रि"},
    {'kantipur': u"5F'b}g", 'unicode': u"छुादैन"},
    {'kantipur': u"5'Fb}g", 'unicode': u"छुादैन"},
    {'kantipur': u"5F'b}}g", 'unicode': u"छुादैन"},
    {'kantipur': u"zLif{sM", 'unicode': u"शीर्षक:"},
    {'kantipur': u"zLif{{sM", 'unicode': u"शीर्षक:"},
    {'kantipur': u"l:j|mgdf", 'unicode': u"स्क्रिनमा"},
    {'kantipur': u"l:j||mgdf", 'unicode': u"स्क्रिनमा"},
    {'kantipur': u"l:j|||mgdf", 'unicode': u"स्क्रिनमा"},
    {'kantipur': u"k[i7df", 'unicode': u"पृष्ठमा"},
    {'kantipur': u"k[[i7df", 'unicode': u"पृष्ठमा"},
    {'kantipur': u"s]xL", 'unicode': u"केही"},
    {'kantipur': u"s]]xL", 'unicode': u"केही"},
    {'kantipur': u"pRrf/0f", 'unicode': u"उच्चारण"},
    {'kantipur': u";'Gg]", 'unicode': u"सुन्ने"},
    {'kantipur': u"lqmofsnfk", 'unicode': u"क्रियाकलाप"},
    {'kantipur': u"7fp&#8220;df", 'unicode': u"ठाउँमा"},
    {'kantipur': u"zAbx¿df", 'unicode': u"शब्दहरूमा"},
    {'kantipur': u";'lgg]", 'unicode': u"सुनिने"},
    {'kantipur': u'k"/f', 'unicode': u"पूरा"},
    {'kantipur': u"µfv", 'unicode': u"राख"},
    {'kantipur': u"ub{}", 'unicode': u"गर्दै"},
    {'kantipur': u"lbOPsf]", 'unicode': u"दिइएको"},
    {'kantipur': u"e¥ofªsf]", 'unicode': u"भर्‍याङको"},
    {'kantipur': u"ljBfyL{", 'unicode': u"विद्यार्थी"},
    {'kantipur': u"lr≈g", 'unicode': u"चिह्न"},
    {'kantipur': u"j[l¢ ug]{", 'unicode': u"वृद्घि गर्ने"},
    {'kantipur': u"sL/f÷hgfj/nfO{", 'unicode': u"कीरा/जनावरलाई"},
    {'kantipur': u"dxŒj", 'unicode': u"महत्त्व"},
    {'kantipur': u"of]u˚n", 'unicode': u"योगफल"},
    {'kantipur': u"dfly–tn", 'unicode': u"माथि–तल"},
    {'kantipur': u"…afbnÚdf", 'unicode': u"‘बादल’मा"},
    {'kantipur': u"*)∞", 'unicode': u"८०%"},
    {'kantipur': u"lr≈g", 'unicode': u"चिह्न"},
    {'kantipur': u"a©Fa®", 'unicode': u"बराबर"},

    {'kantipur': u"…;r]t /xg]Ú", 'unicode': u"‘सचेत रहने’"},
    {'kantipur': u"k|;Ëxý¿", 'unicode': u"प्रसङ्गहरू"},
    {'kantipur': u"u]|", 'unicode': u"ग्रे"},
    {'kantipur': u"a'¤g", 'unicode': u"बुझ्न"},
    {'kantipur': u"/m", 'unicode': u"रु"},
    {'kantipur': u"/mGr]", 'unicode': u"रुन्चे"},
    {'kantipur': u"S|m", 'unicode': u"क्र"},
    {'kantipur': u"k|lS|mof", 'unicode': u"प्रक्रिया"},
    {'kantipur': u"6'S|mf", 'unicode': u"टुक्रा"},
	{'kantipur': u"ub{", 'unicode': u"गर्द"},

    # escaped backslashes
    {'kantipur': u"k8\\s]sf]]", 'unicode': u"पड्केको"},
    {'kantipur': u"k8\\s]sf]", 'unicode': u"पड्केको"},
    {'kantipur': u"a9\\g'xf];\\", 'unicode': u"बढ्नुहोस्"},
    {'kantipur': u"b]vfk5{g\\", 'unicode': u"देखापर्छन्"},
    {'kantipur': u"cª\\u|]hLsf", 'unicode': u"अङ्ग्रेजीका"},
    {'kantipur': u"cK7\\of/f", 'unicode': u"अप्ठ्यारा"},
    {'kantipur': u"v'6\\lsnfdf", 'unicode': u"खुट्किलामा"},
    {'kantipur': u"a'‰g'xf];\\", 'unicode': u"बुझ्नुहोस्"},
    {'kantipur': u"bfo“Fkl6\\6", 'unicode': u"दायाँपट्टि"},
    {'kantipur': u"cª\\u|]hLsf", 'unicode': u"अङ्ग्रेजीका"},
    {'kantipur': u"cª\\u]|hLsf", 'unicode': u"अङ्ग्रेजीका"},

    {'kantipur': u"lbOPsf] k|ltzt a©Fa® rf6{ /Ëfpm M", 'unicode': u"दिइएको प्रतिशत बराबर चार्ट रङ्गाऊ :"},
]

def kantipurTests():
    feedback = u'';

    error_count = 0
    for i, test in enumerate(kantipurTestCases):
        #print str(test)
        result = kantipurToUnicode( test['kantipur'] )
        if result != test['unicode']:
            feedback += "Test " + str(i) + " for " + test['kantipur'] + " failed, expected: " + test['unicode'] + " but got: " + result + "\n"
            error_count += 1

    print "Completed " + str(len(kantipurTestCases)) + " test cases, "+ str(error_count) +" errors.";
    feedback += "Completed " + str(len(kantipurTestCases)) + " test cases.\n";
    return feedback;

if __name__ == '__main__':
    f = codecs.open('tests_py.log', 'w', 'utf-8-sig')
    f.write(kantipurTests())
    f.close()