package  {
	
	import flash.display.MovieClip;
	import Kantipur;
	
	public class Test extends MovieClip {
		
		var kantipurTestCases = [
			{kantipur: "", unicode: ""},
			
			// individual characters (whole kantipur map)
			{kantipur: "!", unicode: "१"},
			{kantipur: '"', unicode: "ू"},
			{kantipur: "#", unicode: "३"},
			{kantipur: "$", unicode: "४"},
			{kantipur: "%", unicode: "५"},
			{kantipur: "&", unicode: "७"},
			{kantipur: "'", unicode: "ु"},
			{kantipur: "(", unicode: "९"},
			{kantipur: ")", unicode: "०"},
			{kantipur: "*", unicode: "८"},
			{kantipur: "+", unicode: "ं"},
			{kantipur: ",", unicode: ","},
			{kantipur: "-", unicode: "("},
			{kantipur: ".", unicode: "।"},
			{kantipur: "/", unicode: "र"},
			{kantipur: "0", unicode: "ण्"},
			{kantipur: "1", unicode: "ज्ञ"},
			{kantipur: "2", unicode: "द्द"},
			{kantipur: "3", unicode: "घ"},
			{kantipur: "4", unicode: "द्ध"},
			{kantipur: "5", unicode: "छ"},
			{kantipur: "6", unicode: "ट"},
			{kantipur: "7", unicode: "ठ"},
			{kantipur: "8", unicode: "ड"},
			{kantipur: "9", unicode: "ढ"},
			{kantipur: ":", unicode: "स्"},
			{kantipur: ";", unicode: "स"},
			{kantipur: "<", unicode: "?"},
			{kantipur: "=", unicode: "."},
			{kantipur: ">", unicode: "श्र"},
			{kantipur: "?", unicode: "रु"},
			{kantipur: "@", unicode: "२"},
			{kantipur: "A", unicode: "ब्"},
			{kantipur: "B", unicode: "द्य"},
			{kantipur: "C", unicode: "ऋ"},
			{kantipur: "D", unicode: "म्"},
			{kantipur: "E", unicode: "भ्"},
			{kantipur: "F", unicode: "ा"},
			{kantipur: "G", unicode: "न्"},
			{kantipur: "H", unicode: "ज्"},
			{kantipur: "I", unicode: "क्ष्"},
			{kantipur: "J", unicode: "व्"},
			{kantipur: "K", unicode: "प्"},
			{kantipur: "L", unicode: "ी"},
			{kantipur: "M", unicode: ":"},
			{kantipur: "N", unicode: "ल्"},
			{kantipur: "O", unicode: "इ"},
			{kantipur: "P", unicode: "ए"},
			{kantipur: "Q", unicode: "त्त"},
			{kantipur: "R", unicode: "च्"},
			{kantipur: "S", unicode: "क्"},
			{kantipur: "T", unicode: "त्"},
			{kantipur: "U", unicode: "ग्"},
			{kantipur: "V", unicode: "ख्"},
			{kantipur: "W", unicode: "ध्"},
			{kantipur: "X", unicode: "ह्"},
			{kantipur: "Y", unicode: "थ्"},
			{kantipur: "Z", unicode: "श्"},
			{kantipur: "[", unicode: "ृ"},
			{kantipur: "\\", unicode: "्"},
			{kantipur: "]", unicode: "े"},
			{kantipur: "^", unicode: "६"},
			{kantipur: "_", unicode: ")"},
			{kantipur: "`", unicode: "ञ"},
			{kantipur: "a", unicode: "ब"},
			{kantipur: "b", unicode: "द"},
			{kantipur: "c", unicode: "अ"},
			{kantipur: "d", unicode: "म"},
			{kantipur: "e", unicode: "भ"},
			{kantipur: "f", unicode: "ा"},
			{kantipur: "g", unicode: "न"},
			{kantipur: "h", unicode: "ज"},
			{kantipur: "i", unicode: "ष्"},
			{kantipur: "j", unicode: "व"},
			{kantipur: "k", unicode: "प"},
			{kantipur: "l", unicode: "ि"},
			{kantipur: "m", unicode: "m"}, // no matching unicode single character
			{kantipur: "n", unicode: "ल"},
			{kantipur: "o", unicode: "य"},
			{kantipur: "p", unicode: "उ"},
			{kantipur: "q", unicode: "त्र"},
			{kantipur: "r", unicode: "च"},
			{kantipur: "s", unicode: "क"},
			{kantipur: "t", unicode: "त"},
			{kantipur: "u", unicode: "ग"},
			{kantipur: "v", unicode: "ख"},
			{kantipur: "w", unicode: "ध"},
			{kantipur: "x", unicode: "ह"},
			{kantipur: "y", unicode: "थ"},
			{kantipur: "z", unicode: "श"},
			{kantipur: "{", unicode: "र्"},
			{kantipur: "|", unicode: "्र"},
			{kantipur: "}", unicode: "ै"},
			{kantipur: "~", unicode: "ञ्"},
			//{kantipur: " ", unicode: ""},
			{kantipur: "¡", unicode: "ज्ञ्"},
			{kantipur: "¢", unicode: "द्घ"},
			{kantipur: "£", unicode: "घ्"},
			{kantipur: "¥", unicode: "र्‍"},
			{kantipur: "§", unicode: "ट्ट"},
			{kantipur: "¨", unicode: "ङ्ग"},
			{kantipur: "ª", unicode: "ङ"},
			{kantipur: "«", unicode: "्र"},
			{kantipur: "¬", unicode: "…"},
			{kantipur: "®", unicode: "र"},
			{kantipur: "°", unicode: "ड्ढ"},
			{kantipur: "±", unicode: "+"},
			{kantipur: "´", unicode: "झ"},
			{kantipur: "¶", unicode: "ठ्ठ"},
			{kantipur: "¿", unicode: "रू"},
			{kantipur: "Â", unicode: "र"},
			{kantipur: "Æ", unicode: "”"},
			{kantipur: "È", unicode: "ष"},
			{kantipur: "Ë", unicode: "ङ्ग"},
			{kantipur: "Ì", unicode: "न्न"},
			{kantipur: "Í", unicode: "ङ्क"},
			{kantipur: "Ò", unicode: "…"},
			{kantipur: "Ô", unicode: "क्ष"},
			{kantipur: "Ø", unicode: "य"},
			{kantipur: "Ú", unicode: "’"},
			{kantipur: "ß", unicode: "द्म"},
			{kantipur: "å", unicode: "द्व"},
			{kantipur: "æ", unicode: "“"},
			{kantipur: "ç", unicode: "ॐ"},
			{kantipur: "÷", unicode: "/"},
			{kantipur: "ø", unicode: "य्"},
			{kantipur: "ı", unicode: "द्र"},
			{kantipur: "Œ", unicode: "त्त्"},
			{kantipur: "œ", unicode: "त्र्"},
			{kantipur: "˘", unicode: "श्र्"},
			{kantipur: "˚", unicode: "फ"},
			{kantipur: "˜", unicode: "ऽ"},
			{kantipur: "‐", unicode: "("},
			{kantipur: "–", unicode: "–"},
			{kantipur: "—", unicode: "—"},
			{kantipur: "‘", unicode: "‘"},
			{kantipur: "’", unicode: "’"},
			{kantipur: "“", unicode: "ँ"},
			{kantipur: "„", unicode: "ध्र"},
			{kantipur: "•", unicode: "ड्ड"},
			{kantipur: "…", unicode: "‘"},
			{kantipur: "‰", unicode: "झ्"},
			{kantipur: "‹", unicode: "ङ्घ"},
			{kantipur: "›", unicode: "ऽ"},
			{kantipur: "⁄", unicode: "!"},
			{kantipur: "∞", unicode: "%"},
			{kantipur: "≈", unicode: "ह्"},
			{kantipur: "≠", unicode: "="},
			{kantipur: "≤", unicode: ";"},
			{kantipur: "≥", unicode: "."},
			{kantipur: "⋲", unicode: "ह्"},
			{kantipur: "◊", unicode: "ङ्ख"},
			{kantipur: "", unicode: "फ्"},
			{kantipur: "", unicode: "ट्ठ"},
			{kantipur: "Î", unicode: "फ्"},
			{kantipur: "¤", unicode: "झ्"},
			{kantipur: "™", unicode: "र"},
			{kantipur: "/\\", unicode: "र्"},
			{kantipur: "/\\o", unicode: "ऱ्य"},
			
			// words
			{kantipur: "l:j|m", unicode: "स्क्रि"},
			{kantipur: "5F'b}g", unicode: "छुादैन"},
			{kantipur: "5'Fb}g", unicode: "छुादैन"},
			{kantipur: "5F'b}}g", unicode: "छुादैन"},
			{kantipur: "zLif{sM", unicode: "शीर्षक:"},
			{kantipur: "zLif{{sM", unicode: "शीर्षक:"},
			{kantipur: "l:j|mgdf", unicode: "स्क्रिनमा"},
			{kantipur: "l:j||mgdf", unicode: "स्क्रिनमा"},
			{kantipur: "l:j|||mgdf", unicode: "स्क्रिनमा"},
			{kantipur: "k[i7df", unicode: "पृष्ठमा"},
			{kantipur: "k[[i7df", unicode: "पृष्ठमा"},
			{kantipur: "s]xL", unicode: "केही"},
			{kantipur: "s]]xL", unicode: "केही"},
			{kantipur: "pRrf/0f", unicode: "उच्चारण"},
			{kantipur: ";'Gg]", unicode: "सुन्ने"},
			{kantipur: "lqmofsnfk", unicode: "क्रियाकलाप"},
			{kantipur: "7fp&#8220;df", unicode: "ठाउँमा"},
			{kantipur: "zAbx¿df", unicode: "शब्दहरूमा"},
			{kantipur: ";'lgg]", unicode: "सुनिने"},
			{kantipur: 'k"/f', unicode: "पूरा"},
			{kantipur: "µfv", unicode: "राख"},
			{kantipur: "ub{}", unicode: "गर्दै"},
			{kantipur: "lbOPsf]", unicode: "दिइएको"},
			{kantipur: "e¥ofªsf]", unicode: "भर्‍याङको"},
			{kantipur: "ljBfyL{", unicode: "विद्यार्थी"},
			{kantipur: "lr≈g", unicode: "चिह्न"},
			{kantipur: "j[l¢ ug]{", unicode: "वृद्घि गर्ने"},
			{kantipur: "sL/f÷hgfj/nfO{", unicode: "कीरा/जनावरलाई"},
			{kantipur: "dxŒj", unicode: "महत्त्व"},
			{kantipur: "of]u˚n", unicode: "योगफल"},
			{kantipur: "dfly–tn", unicode: "माथि–तल"},
			{kantipur: "…afbnÚdf", unicode: "‘बादल’मा"},
			{kantipur: "*)∞", unicode: "८०%"},
			{kantipur: "lr≈g", unicode: "चिह्न"},
			{kantipur: "a©Fa®", unicode: "बराबर"},
			
			{kantipur: "…;r]t /xg]Ú", unicode: "‘सचेत रहने’"},
			{kantipur: "k|;Ëxý¿", unicode: "प्रसङ्गहरू"},
			{kantipur: "u]|", unicode: "ग्रे"},
			{kantipur: "a'¤g", unicode: "बुझ्न"},
			{kantipur: "a'¤mfpg]", unicode: "बुझाउने"},
			{kantipur: "/m", unicode: "रु"},
			{kantipur: "/mGr]", unicode: "रुन्चे"},
			{kantipur: "S|m", unicode: "क्र"},
			{kantipur: "k|lS|mof", unicode: "प्रक्रिया"},
			{kantipur: "6'S|mf", unicode: "टुक्रा"},
			{kantipur: "ub{", unicode: "गर्द"},
			
			 // escaped backslashes
			{kantipur: "k8\\s]sf]]", unicode: "पड्केको"},
			{kantipur: "k8\\s]sf]", unicode: "पड्केको"},
			{kantipur: "a9\\g'xf];\\", unicode: "बढ्नुहोस्"},
			{kantipur: "b]vfk5{g\\", unicode: "देखापर्छन्"},
			{kantipur: "cª\\u|]hLsf", unicode: "अङ्ग्रेजीका"},
			{kantipur: "cK7\\of/f", unicode: "अप्ठ्यारा"},
			{kantipur: "v'6\\lsnfdf", unicode: "खुट्किलामा"},
			{kantipur: "a'‰g'xf];\\", unicode: "बुझ्नुहोस्"},
			{kantipur: "bfo“Fkl6\\6", unicode: "दायाँपट्टि"},
			{kantipur: "cª\\u|]hLsf", unicode: "अङ्ग्रेजीका"},
			{kantipur: "cª\\u]|hLsf", unicode: "अङ्ग्रेजीका"},
			
			{kantipur: "lbOPsf] k|ltzt a©Fa® rf6{ /Ëfpm M", unicode: "दिइएको प्रतिशत बराबर चार्ट रङ्गाऊ :"},
			
			// config format
			{kantipur: "zLif{sM *e*Basic Sounds IV*n*", unicode: "शीर्षक: Basic Sounds IV"}
		];
		
		
		public function Test() 
		{
			resultText.text = performTests();
		}
		
		public function performTests():String
		{
			var feedback = "";
	
			for( var i=0; i<kantipurTestCases.length; i++ ){
				var unicode = Kantipur.kantipurConfigToUnicode( kantipurTestCases[i].kantipur );
				if ( unicode != kantipurTestCases[i].unicode ){
					feedback += "Test " + i + " for " + kantipurTestCases[i].kantipur + " failed, expected: " + kantipurTestCases[i].unicode + " but got: " + unicode + "<br/>\n";
				}
			}
		
			feedback += "Completed " + kantipurTestCases.length + " test cases.\n";
			return feedback;
			
		}
	}
	
}
